# Generated by Django 5.1.3 on 2024-11-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_cliente_productos_vendedor_delete_bibliotecaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregado',
            old_name='Entregado',
            new_name='entregado',
        ),
    ]
